// src/App.tsx
import React, { Component, ReactNode } from 'react';
import { StyleSheet, View } from 'react-native';
import { Constants } from './Constants';
import { World } from 'ecsy';
import { TransformComponent } from './components/TransformComponent';
import { RenderComponent as RenderComponent } from './components/RenderComponent';
import { SelectableComponent } from './components/SelectableComponent';
import { RenderSystem } from './systems/RenderSystem';
import { SizeComponent } from './components/SizeComponent';
import { EntityFactory } from './EntityFactory';
import { PlayerControlSystem } from './systems/PlayerControlSystem';
import { SelectorComponent } from './components/SelectorComponent';
import { ShapeComponent } from './components/ShapeComponent';
import { TextComponent } from './components/TextComponent';
import { FpsComponent } from './components/FpsComponent';
import { FpsSystem } from './systems/FpsSystem';
import { TweenComponent } from './components/TweenComponent';
import { TweenSystem } from './systems/TweenSystem';
import { MovableComponent } from './components/MovableComponent';
import { LayerComponent } from './components/LayerComponent';
import { VisibilityComponent } from './components/VisibilityComponent';
import { HealthComponent } from './components/HealthComponent';
import { AliveComponent } from './components/AliveComponent';
import { HealthSystem } from './systems/HealthSystem';
import { AliveSystem } from './systems/AliveSystem';
import { ColliderComponent } from './components/ColliderComponent';
import { Grid } from './Grid';
import { Vector2 } from './math/Vector2';
import { DebugComponent } from './components/DebugComponent';

type AppProps = {};

export default class App extends Component<AppProps> {
	private canvas: HTMLCanvasElement;
	private world: World;
	private lastFrameTime = 0;

	constructor(props: AppProps) {
		super(props);

		this.world = new World();

		this.handleCanvas = this.handleCanvas.bind(this);
		this.frame = this.frame.bind(this);
	}

	private handleCanvas(canvas: HTMLCanvasElement): void {
		this.canvas = canvas;

		this.world
			.registerComponent(TransformComponent)
			.registerComponent(ShapeComponent)
			.registerComponent(RenderComponent)
			.registerComponent(SizeComponent)
			.registerComponent(SelectableComponent)
			.registerComponent(SelectorComponent)
			.registerComponent(MovableComponent)
			.registerComponent(TextComponent)
			.registerComponent(FpsComponent)
			.registerComponent(LayerComponent)
			.registerComponent(TweenComponent)
			.registerComponent(VisibilityComponent)
			.registerComponent(HealthComponent)
			.registerComponent(AliveComponent)
			.registerComponent(ColliderComponent)
			.registerComponent(DebugComponent)
			.registerSystem(RenderSystem, { canvas: canvas })
			.registerSystem(PlayerControlSystem, { canvas: canvas })
			.registerSystem(FpsSystem)
			.registerSystem(TweenSystem)
			.registerSystem(HealthSystem)
			.registerSystem(AliveSystem);

		EntityFactory.createSelector(this.world, {
			position: {
				x: 100,
				y: 100,
			},
		});
		EntityFactory.createFpsCouter(this.world, {
			position: {
				x: Constants.GAME_WIDTH - 25,
				y: 20,
			},
		});

		this.world.createEntity()
			.addComponent(RenderComponent)
			.addComponent(DebugComponent);

		const grid = new Grid({
			width: Constants.GAME_WIDTH / Constants.UNIT_SIZE,
			height: Constants.GAME_HEIGHT / Constants.UNIT_SIZE,
			cellSize: Constants.UNIT_SIZE,
			originPosition: Vector2.ZERO,
		});

		this.startLevel();

		// Run!
		this.lastFrameTime = performance.now();
		this.frame();
	}

	private startLevel(): void {
		Array.from(Array(100)).forEach(() => {
			let x = Math.round(
				Math.random() * Constants.GAME_WIDTH
			);
			x = x - (x % Constants.UNIT_SIZE) + (Constants.UNIT_SIZE / 2);
			let y = Math.round(
				Math.random() * Constants.GAME_HEIGHT
			) + (Constants.UNIT_SIZE / 2);
			y = y - (y % Constants.UNIT_SIZE) + (Constants.UNIT_SIZE / 2);

			EntityFactory.createUnit(this.world, {
				position: {
					x: x,
					y: y
				},
				color: 'red',
			});
		});
	}

	private frame(): void {
		// Compute delta and elapsed time
		const time = performance.now();
		const delta = time - this.lastFrameTime;

		// Run all the systems
		this.world.execute(delta, time);

		this.lastFrameTime = time;
		requestAnimationFrame(this.frame);
	}

	public render(): ReactNode {
		return (
			<View style={styles.container}>
				<canvas
					width={Constants.GAME_WIDTH}
					height={Constants.GAME_HEIGHT}
					style={{ backgroundColor: '#d4d4d4' }}
					ref={this.handleCanvas}
				/>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center',
	},
	game: {
		width: Constants.GAME_WIDTH,
		height: Constants.GAME_HEIGHT,
		backgroundColor: '#d4d4d4',
		flex: undefined,
		overflow: 'hidden',
	},
	grid: {},
	gridRow: {
		flexDirection: 'row',
	},
	tile: {
		borderWidth: 1,
		width: 50,
		height: 50,
	},
});

// src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { World } from 'ecsy';
import * as PIXI from 'pixi.js';
import { DashLine }  from 'pixi-dashed-line';

import { Constants } from './Constants';
import { TransformComponent } from './systems/TransformComponent';
import { SizeComponent } from './systems/SizeComponent';
import { SelectableComponent } from './systems/selection/SelectableComponent';
import { MovableComponent } from './systems/movement/MovableComponent';
import { HealthComponent } from './systems/health/HealthComponent';
import { GridComponent } from './systems/GridComponent';
import { MoveTransformVelocityComponent } from './systems/movement/MoveTransformVelocityComponent';
import { MovePositionDirectComponent } from './systems/movement/MovePositionDirectComponent';
import { PlayerMovementMouseComponent } from './systems/player/PlayerMovementMouseComponent';
import { PlayerMovementKeysComponent } from './systems/player/PlayerMovementKeysComponent';
import { MoveVelocityComponent } from './systems/movement/MoveVelocityComponent';
import { PathfindingComponent } from './systems/PathfindingComponent';
import { PlayerSelectionSystem } from './systems/selection/PlayerSelectionSystem';
import { HealthSystem } from './systems/health/HealthSystem';
import { AliveSystem } from './systems/alive/AliveSystem';
import { MoveTransformVelocitySystem } from './systems/movement/MoveTransformVelocitySystem';
import { InputSystem } from './systems/InputSystem';
import { PlayerMovementKeysSystem } from './systems/player/PlayerMovementKeysSystem';
import { MovePositionDirectSystem } from './systems/movement/MovePositionDirectSystem';
import { PlayerMovementMouseSystem } from './systems/player/PlayerMovementMouseSystem';
import { MoveVelocitySystem } from './systems/movement/MoveVelocitySystem';
import { EntityFactory } from './EntityFactory';
import { Pathfinding } from './ai/Pathfinding';
import { SpriteComponent } from './systems/render/sprite/SpriteComponent';
import { SpriteSystem } from './systems/render/sprite/SpriteSystem';
import { GraphicsComponent } from './systems/render/graphics/GraphicsComponent';
import { GraphicsSystem } from './systems/render/graphics/GraphicsSystem';
import { AliveComponent } from './systems/alive/AliveComponent';
import { Vector2 } from './math/Vector2';
import { toGridPosition } from './systems/player/utils';

const app = new PIXI.Application({
	resizeTo: window,
});

app.renderer.backgroundColor = 0x008800;

const world = new World();
let lastFrameTime = 0;

onMounted(() => {
	document.getElementById('App')!.appendChild(app.view);

	app.view.addEventListener('contextmenu', (event) => {
		event.preventDefault();
	});

	lastFrameTime = performance.now();
	app.ticker.add(() => {
		frame();
	});

	app.loader.add('swordsmen', 'assets/swordsmen.blue.move.west_06.png').load((loader, resources) => {
		startLevel(resources);
	});

	world
		.registerComponent(TransformComponent)
		.registerComponent(SizeComponent)
		.registerComponent(SelectableComponent)
		.registerComponent(MovableComponent)
		.registerComponent(HealthComponent)
		.registerComponent(AliveComponent)
		.registerComponent(MoveTransformVelocityComponent)
		.registerComponent(MovePositionDirectComponent)
		.registerComponent(PlayerMovementMouseComponent)
		.registerComponent(PlayerMovementKeysComponent)
		.registerComponent(MoveVelocityComponent)
		.registerComponent(PathfindingComponent)
		.registerComponent(SpriteComponent)
		.registerComponent(GraphicsComponent)
		.registerComponent(GridComponent)
		.registerSystem(PlayerSelectionSystem, { app })
		.registerSystem(HealthSystem)
		.registerSystem(AliveSystem)
		.registerSystem(MoveTransformVelocitySystem)
		.registerSystem(InputSystem, { canvas: app.view })
		.registerSystem(PlayerMovementKeysSystem)
		.registerSystem(MovePositionDirectSystem)
		.registerSystem(PlayerMovementMouseSystem, { app })
		.registerSystem(MoveVelocitySystem)
		.registerSystem(SpriteSystem, { app })
		.registerSystem(GraphicsSystem, { app });

    const pathfinding = new Pathfinding(Math.ceil(app.renderer.width / Constants.CELL_SIZE), Math.ceil(app.renderer.height / Constants.CELL_SIZE));

	world.createEntity()
		.addComponent(PathfindingComponent, {
			pathfinding: pathfinding,
		})
		// @ts-ignore
		.addComponent(GridComponent, { grid: pathfinding.grid });

	drawGrid();
	window.onresize = () => drawGrid();
});

let gridGraphics: PIXI.Graphics|null = null;
const drawGrid = (): void => {
	if (gridGraphics == null) {
		gridGraphics = app.stage.addChildAt(new PIXI.Graphics(), 0);
	} else {
		gridGraphics.clear();
	}

	const dash = new DashLine(gridGraphics, {
		dash: [5, 5],
		width: 1,
		color: 0x666666777777,
	})

	for(let height = Constants.CELL_SIZE; height < app.screen.height; height += Constants.CELL_SIZE) {
		// horizontal lines
		dash.moveTo(0, height)
			.lineTo(app.screen.width, height);
	}

	for(let width = Constants.CELL_SIZE; width < app.screen.width; width += Constants.CELL_SIZE) {
		// vertical lines
		dash.moveTo(width, 0)
			.lineTo(width, app.screen.height);
	}
};

const startLevel = (resources: PIXI.utils.Dict<PIXI.LoaderResource>): void => {
	Array.from(Array(100)).forEach(() => {
		const vector = toGridPosition(new Vector2(
			Math.round(
				Math.random() * app.screen.width,
			), 
			Math.round(
				Math.random() * app.screen.height,
			) + (Constants.CELL_SIZE / 2)
		));

		EntityFactory.createUnit(world, {
			position: vector,
			color: 'red',
			texture: resources.swordsmen.texture!,
		});
	});
}

const frame = (): void => {
	// Compute delta and elapsed time
	const time = performance.now();
	const delta = time - lastFrameTime;

	// Run all the systems
	world.execute(delta, time);

	lastFrameTime = time;
}

</script>

<template>
  <div id="App"/>
</template>

<style>
	body {
		margin: 0;
		overflow: hidden;
	}
</style>
